### PR TITLE
Add Python 2.6 to the supported build environment

### PR DESCRIPTION
**Pull request by arcivanov**
Closes ionelmc/python-tblib#7

### CODE REVIEW

**Comment by ionelmc** [comment]
Alright. In master now (slightly reformated). Just made a 1.1.0 release.

**Comment by ionelmc** [comment]
Thanks

**Comment by ionelmc** [comment]
(I've messed up the authorship, sorry @arcivanov)

**Comment by arcivanov** [comment]
No worries. Thanks, already using it. :smile:

**Pull request closed without merging**
