### PR TITLE
Add Frame.f_lineno

### LINKED ISSUE #56: f_lineno is missing
The `Frame` object does not copy `f_lineno` from the underlying frame object. This causes a bug when pytest can't handle an exception raise from gevent's ThreadPool. Gevent guys use a vendored version but I'd like to have this issue fixed in the main repo too.

### PR DESCRIPTION
**Pull request by imachug**
Closes #56.

### CODE REVIEW

**Comment by ionelmc** [comment]
Can you also update the tests?

**Comment by imachug** [comment]
Will do.

**Comment by imachug** [comment]
I can't run the tests locally (unfortunately) so I have to use Travis CI. I'll send a comment when I get the tests passing.

**Comment by imachug** [comment]
The tests are passing now. @ionelmc

**Comment by imachug** [comment]
@ionelmc Do you think the PR looks good?

**Comment by ionelmc** [comment]
Looks good. Can you also update changelog/authors with what you like?

Also, correct to assume you'd follow up this with a gevent PR or something? CC @jamadden

**Comment by imachug** [comment]
> Can you also update changelog/authors with what you like?

Done, please check that I've done it correctly.

> Also, correct to assume you'd follow up this with a gevent PR or something?

True. I want to get #58 merged before though.

**Comment by imachug** [comment]
Merging into #58.

**Pull request closed without merging**
