### PR TITLE
Patch to add support for pdb

### PR DESCRIPTION
**Pull request by te-je**
Adds support for running `pdb.post_mortem(tb)` on the tracebacks wrapped in this package.

Here's a JSON serialized traceback with three debug levels:

```json
{
  "tb_frame": {
    "f_locals": {
      "__name__": "__main__",
      "__package__": null,
      "foo": "knock knock",
      "__spec__": null,
      "bar": "who's there",
      "__doc__": null
    },
    "f_code": {
      "co_stacksize": 9,
      "co_nlocals": 0,
      "co_flags": 64,
      "co_lnotab": "\u0003\u0001\u0006\u0001\u0006\u0001\u0016\u0001\u0003\u0001",
      "co_name": "<module>",
      "co_firstlineno": 1,
      "co_filename": "<stdin>"
    },
    "f_globals": {
      "__name__": "__main__",
      "__package__": null,
      "foo": "knock knock",
      "__spec__": null,
      "bar": "who's there",
      "__doc__": null
    }
  },
  "tb_next": {
    "tb_frame": {
      "f_locals": {
        "seps": "\\/",
        "path": "yo mama",
        "p": 1000,
        "result_path": "yo mama",
        "paths": [
          1000
        ],
        "result_drive": "",
        "colon": ":",
        "sep": "\\"
      },
      "f_code": {
        "co_stacksize": 13,
        "co_nlocals": 10,
        "co_flags": 71,
        "co_lnotab": "\u0000\u0001\u000f\u0001\u0006\u0001\u0006\u0001\t\u0002\u0006\u0001\u0006\u0001\u0006\u0001\u0003\u0001\u0006\u0001\u0012\u0001\u0012\u0001\r\u0001\u0012\u0001\u0016\u0002\r\u0001\u0006\u0001\u0006\u0001\u0006\u0001\u0012\u0001\u0018\u0002\u0006\u0001\u0006\u0001\u0003\u0002\u0006\u0002\u0016\u0001\n\u0001\u000e\u0002\u0016\u0001\u001c\u0001\f\u0001\f\u0001\u0016\u0001\u0013\u0001",
        "co_name": "join",
        "co_firstlineno": 74,
        "co_filename": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\ntpath.py"
      },
      "f_globals": {
        "altsep": "/",
        "__name__": "ntpath",
        "curdir": ".",
        "defpath": ".;C:\\bin",
        "extsep": ".",
        "pathsep": ";",
        "__package__": "",
        "__doc__": "Common pathname manipulations, WindowsNT/95 version.\n\nInstead of importing this module directly, import os and refer to this\nmodule as os.path.\n",
        "supports_unicode_filenames": true,
        "__cached__": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\__pycache__\\ntpath.cpython-35.pyc",
        "pardir": "..",
        "devnull": "nul",
        "__file__": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\ntpath.py",
        "__all__": [
          "normcase",
          "isabs",
          "join",
          "splitdrive",
          "split",
          "splitext",
          "basename",
          "dirname",
          "commonprefix",
          "getsize",
          "getmtime",
          "getatime",
          "getctime",
          "islink",
          "exists",
          "lexists",
          "isdir",
          "isfile",
          "ismount",
          "expanduser",
          "expandvars",
          "normpath",
          "abspath",
          "splitunc",
          "curdir",
          "pardir",
          "sep",
          "pathsep",
          "defpath",
          "altsep",
          "extsep",
          "devnull",
          "realpath",
          "supports_unicode_filenames",
          "relpath",
          "samefile",
          "sameopenfile",
          "samestat",
          "commonpath"
        ],
        "sep": "\\"
      }
    },
    "tb_next": {
      "tb_frame": {
        "f_locals": {
          "hasstr": true,
          "args": [
            "yo mama",
            1000
          ],
          "funcname": "join",
          "s": 1000,
          "hasbytes": false
        },
        "f_code": {
          "co_stacksize": 5,
          "co_nlocals": 5,
          "co_flags": 71,
          "co_lnotab": "\u0000\u0001\n\u0001\r\u0001\u000f\u0001\t\u0001\u000f\u0001\t\u0002\u0006\u0001\u001d\u0001\f\u0001",
          "co_name": "_check_arg_types",
          "co_firstlineno": 134,
          "co_filename": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\genericpath.py"
        },
        "f_globals": {
          "__name__": "genericpath",
          "__package__": "",
          "__all__": [
            "commonprefix",
            "exists",
            "getatime",
            "getctime",
            "getmtime",
            "getsize",
            "isdir",
            "isfile",
            "samefile",
            "sameopenfile",
            "samestat"
          ],
          "__cached__": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\__pycache__\\genericpath.cpython-35.pyc",
          "__file__": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\genericpath.py",
          "__doc__": "\nPath operations common to more than one OS\nDo not use directly.  The OS specific modules import the appropriate\nfunctions from this module themselves.\n"
        }
      },
      "tb_next": null,
      "tb_lineno": 143,
      "tb_lasti": 99
    },
    "tb_lineno": 113,
    "tb_lasti": 403
  },
  "tb_lineno": 4,
  "tb_lasti": 27
}
```

### CODE REVIEW

**Comment by ionelmc** [comment]
Just to Be sure, this only allow inspecting the frames right?

On Sunday, July 19, 2015, Te-jé Rodgers <notifications@github.com> wrote:

> Adds support for running pdb.post_mortem(tb) on the tracebacks wrapped in
> this package.
>
> Here's a JSON serialized traceback with three debug levels:
>
> {
>   "tb_frame": {
>     "f_locals": {
>       "__name__": "__main__",
>       "__package__": null,
>       "foo": "knock knock",
>       "__spec__": null,
>       "bar": "who's there",
>       "__doc__": null
>     },
>     "f_code": {
>       "co_stacksize": 9,
>       "co_nlocals": 0,
>       "co_flags": 64,
>       "co_lnotab": "\u0003\u0001\u0006\u0001\u0006\u0001\u0016\u0001\u0003\u0001",
>       "co_name": "<module>",
>       "co_firstlineno": 1,
>       "co_filename": "<stdin>"
>     },
>     "f_globals": {
>       "__name__": "__main__",
>       "__package__": null,
>       "foo": "knock knock",
>       "__spec__": null,
>       "bar": "who's there",
>       "__doc__": null
>     }
>   },
>   "tb_next": {
>     "tb_frame": {
>       "f_locals": {
>         "seps": "\\/",
>         "path": "yo mama",
>         "p": 1000,
>         "result_path": "yo mama",
>         "paths": [
>           1000
>         ],
>         "result_drive": "",
>         "colon": ":",
>         "sep": "\\"
>       },
>       "f_code": {
>         "co_stacksize": 13,
>         "co_nlocals": 10,
>         "co_flags": 71,
>         "co_lnotab": "\u0000\u0001\u000f\u0001\u0006\u0001\u0006\u0001\t\u0002\u0006\u0001\u0006\u0001\u0006\u0001\u0003\u0001\u0006\u0001\u0012\u0001\u0012\u0001\r\u0001\u0012\u0001\u0016\u0002\r\u0001\u0006\u0001\u0006\u0001\u0006\u0001\u0012\u0001\u0018\u0002\u0006\u0001\u0006\u0001\u0003\u0002\u0006\u0002\u0016\u0001\n\u0001\u000e\u0002\u0016\u0001\u001c\u0001\f\u0001\f\u0001\u0016\u0001\u0013\u0001",
>         "co_name": "join",
>         "co_firstlineno": 74,
>         "co_filename": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\ntpath.py"
>       },
>       "f_globals": {
>         "altsep": "/",
>         "__name__": "ntpath",
>         "curdir": ".",
>         "defpath": ".;C:\\bin",
>         "extsep": ".",
>         "pathsep": ";",
>         "__package__": "",
>         "__doc__": "Common pathname manipulations, WindowsNT/95 version.\n\nInstead of importing this module directly, import os and refer to this\nmodule as os.path.\n",
>         "supports_unicode_filenames": true,
>         "__cached__": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\__pycache__\\ntpath.cpython-35.pyc",
>         "pardir": "..",
>         "devnull": "nul",
>         "__file__": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\ntpath.py",
>         "__all__": [
>           "normcase",
>           "isabs",
>           "join",
>           "splitdrive",
>           "split",
>           "splitext",
>           "basename",
>           "dirname",
>           "commonprefix",
>           "getsize",
>           "getmtime",
>           "getatime",
>           "getctime",
>           "islink",
>           "exists",
>           "lexists",
>           "isdir",
>           "isfile",
>           "ismount",
>           "expanduser",
>           "expandvars",
>           "normpath",
>           "abspath",
>           "splitunc",
>           "curdir",
>           "pardir",
>           "sep",
>           "pathsep",
>           "defpath",
>           "altsep",
>           "extsep",
>           "devnull",
>           "realpath",
>           "supports_unicode_filenames",
>           "relpath",
>           "samefile",
>           "sameopenfile",
>           "samestat",
>           "commonpath"
>         ],
>         "sep": "\\"
>       }
>     },
>     "tb_next": {
>       "tb_frame": {
>         "f_locals": {
>           "hasstr": true,
>           "args": [
>             "yo mama",
>             1000
>           ],
>           "funcname": "join",
>           "s": 1000,
>           "hasbytes": false
>         },
>         "f_code": {
>           "co_stacksize": 5,
>           "co_nlocals": 5,
>           "co_flags": 71,
>           "co_lnotab": "\u0000\u0001\n\u0001\r\u0001\u000f\u0001\t\u0001\u000f\u0001\t\u0002\u0006\u0001\u001d\u0001\f\u0001",
>           "co_name": "_check_arg_types",
>           "co_firstlineno": 134,
>           "co_filename": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\genericpath.py"
>         },
>         "f_globals": {
>           "__name__": "genericpath",
>           "__package__": "",
>           "__all__": [
>             "commonprefix",
>             "exists",
>             "getatime",
>             "getctime",
>             "getmtime",
>             "getsize",
>             "isdir",
>             "isfile",
>             "samefile",
>             "sameopenfile",
>             "samestat"
>           ],
>           "__cached__": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\__pycache__\\genericpath.cpython-35.pyc",
>           "__file__": "C:\\Users\\Te-j\u00e9\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\genericpath.py",
>           "__doc__": "\nPath operations common to more than one OS\nDo not use directly.  The OS specific modules import the appropriate\nfunctions from this module themselves.\n"
>         }
>       },
>       "tb_next": null,
>       "tb_lineno": 143,
>       "tb_lasti": 99
>     },
>     "tb_lineno": 113,
>     "tb_lasti": 403
>   },
>   "tb_lineno": 4,
>   "tb_lasti": 27
> }
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ionelmc/python-tblib/pull/6
> Commit Summary
>
>    - Patch to add support for pdb
>
> File Changes
>
>    - *M* src/tblib/__init__.py
>    <https://github.com/ionelmc/python-tblib/pull/6/files#diff-0> (51)
>
> Patch Links:
>
>    - https://github.com/ionelmc/python-tblib/pull/6.patch
>    - https://github.com/ionelmc/python-tblib/pull/6.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ionelmc/python-tblib/pull/6>.
>


-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by te-je** [comment]
Yes that's correct. It allows for checking /some/ of the locals/globals in the traceback at each frame (those that can't be serialized are omitted).

**Comment by ionelmc** [comment]
Would there be any way to add a flag to disable adding the variables (since they would inflate the output size a lots and they are only needed if you actuall inspect the frames)?

**Comment by te-je** [comment]
I think it would require flags on all three of the classes, since they all do add extra fields. They can probably pass that flag off to each other, without needing to store it, since the inflation of these extra fields happen in the constructor.

**Comment by ionelmc** [comment]
Ok, I don't want to be negative but humour this question: 
  
If you want to debug something remotely, wouldn't it be better to use a remote debugger? (eg: https://pypi.python.org/pypi/remote-pdb or the many other implementations)

I'm just asking this because from what I've seen you shouldn't pickle stuff as it can create its own class of bugs. IOW, when debugging, "minimization" should be a goal (eg: don't do extra un-necessary stuff because then it's hard to find the actual cause).

**Comment by te-je** [comment]
I do see your point. I'm closing this.

**Comment by pietroalbini** [comment]
I would love to see this PR merged.

I sometimes need to debug exceptions happened hours before, and having also the variables in the frames available is a great aid to debugging. The project I'm working on is a long-running server which might raise some exceptions from time to time (and it catches them), and it would be really useful to store serialized exceptions in order to debug them when I have some spare time.

If @te-je isn't interested in this anymore I'm willing to fix this PR's issues.

**Comment by ionelmc** [comment]
@pietroalbini wouldn't something like https://getsentry.com/ be a better way to solve it?

Because what tblib does right now (and what I intended for it to do) is allowing reraising/printing of these fake frames. Inspecting and using the frames like they were real entails lots of perils :-) 

Please prove first that you can actually do anything with fatter frames. This means taking the older PR, doing some testing with PDB, and then probably giving up :-)

**Comment by pietroalbini** [comment]
Sorry for the late response, but I had some busy weeks!
This kinda works for my project, because almost every object in it is pickleable for other reasons, but I know this wouldn't work reliably in the other ones. If you don't want to merge this don't worry, I'll just use tblib from this commit in my project :)

**Pull request closed without merging**
